### ISSUE TITLE
imGuru crash on Big Sur

### ISSUE THREAD

**Issue by sdugoten** [IGRSoft/imGuru#10]
The app launch OK on Big Sur.  However, when you login and authenticated by Imgur, it will crash.  And then when you reopen again, it will crash again.

**Comment by JayBrown** [comment]
I didn't have this problem (imGuru v1.0.4 from the MAS on macOS 11.2.2).

**Comment by ikorich** [comment]
Crash has not been found.
Closed outdated issue.
