### ISSUE TITLE
Future: universal binary + anonymous uploads

### ISSUE THREAD

**Issue by JayBrown** [IGRSoft/imGuru#11]
Quick question up front: is this the repo for the Mac App Store release (currently at v1.0.4)?

(1) It's working fine for me on Big Sur, and I'm still on Intel, but nonetheless: will there be a Universal 2 release? Because I won't stay on Intel forever. ;)

(2) I might have asked this before… not sure if here or elsewhere: lots of tools (but currently no macOS Share extensions afaik) use imgur's public & anonymous API. Are there any plans to include anonymous imgur uploads in imGuru?

**Comment by ikorich** [comment]
Hey @JayBrown ,

1. from 1.0.5 it support Intel and Silicon, using standard Xcode settings.

2. I'm not planing add anonymous imgur uploads. Current obj-c lib doesn't support it and to add that option need rewrite app to swift and write own imgur network layer.
