### ISSUE TITLE
Авторизация не работает

### ISSUE THREAD

**Issue by AMD-NICK** [IGRSoft/imGuru#12]
Оставлял отзыв в AppStore, увидел ответ, заранее исправил оценку. На всякий случай решил добавить демку неработающей авторизации

https://user-images.githubusercontent.com/9200174/176400298-bd2a0947-245b-4a10-9bd8-75623adb5ada.mp4

MacOS Monterey 12.0.1

---

P.S. На лендинге нет контактов для связи

**Comment by ikorich** [comment]
@AMD-NICK, спасибо за фидбек, постараюсь исправить в скором времени
