### ISSUE TITLE
"Высокое потребление энергии"

### ISSUE THREAD

**Issue by AMD-NICK** [IGRSoft/imGuru#13]
Два раза увидел такое предупреждение. Issue можно сразу закрыть, просто держу в курсе. Никаких особых действий при этом не производил, приложение в этот момент не использовалось. Возможно, баг MacOS

![telegram-cloud-photo-size-2-5431825975563370491-x](https://user-images.githubusercontent.com/9200174/187967512-460fec33-8fba-401b-afcc-4359c19fa0d8.jpg)

**Comment by ikorich** [comment]
@AMD-NICK спасибо за фидбек, на следующем релизе попрофайлю этот момент

**Comment by ikorich** [comment]
@AMD-NICK продєбажив два дні, нічого не віявив.
закриваю тікет

**Comment by AMD-NICK** [comment]
Да, у меня тоже не получалось воспроизвести это. Если получится узнать точные шаги, я сообщу
