### ISSUE TITLE
Upload doesn't work

### ISSUE THREAD

**Issue by JayBrown** [IGRSoft/imGuru#3]
Using the Mac App Store version.

Upload doesn't seem to work: tested on El Capitan and High Sierra (10.13.5). The appex shows up in the Share menu, the application is registered with my imgur account, I am logged in, imGuru says, but when uploading an image, imGuru doesn't return a URL. Basically, nothing happens.

What gives?

**Comment by ikorich** [comment]
@JayBrown thank you for feedback

I check it in few days

**Comment by gingerbeardman** [comment]
Can be closed.
